# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AnatomyItemTypes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'AnatomyItemTypes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CAMairDataTypes_pb2 as CAMairDataTypes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x41natomyItemTypes.proto\x12\x32ThreeShape.CAMair.Api.Protocol.v1.AnatomyItemTypes\x1a\x15\x43\x41MairDataTypes.proto\"\xae\x01\n\x15NeededAnatomyItemData\x12\x12\n\nmarginLine\x18\x01 \x01(\x08\x12!\n\x19toothAnatomicalDirections\x18\x02 \x01(\x08\x12^\n\ncontactMap\x18\x03 \x01(\x0b\x32J.ThreeShape.CAMair.Api.Protocol.v1.AnatomyItemTypes.DistancesMapNeededData\"i\n\x16\x44istancesMapNeededData\x12\x13\n\x0bverticesIds\x18\x01 \x01(\x08\x12\x1b\n\x13\x64istancesToNeighbor\x18\x02 \x01(\x08\x12\x1d\n\x15\x64istancesToAntagonist\x18\x03 \x01(\x08\"^\n\x0b\x44istanceMap\x12\x13\n\x0bverticesIds\x18\x01 \x03(\x05\x12\x1b\n\x13\x64istancesToNeighbor\x18\x02 \x03(\x02\x12\x1d\n\x15\x64istancesToAntagonist\x18\x03 \x03(\x02\"\x88\x02\n\x0f\x41natomyItemData\x12?\n\nmarginLine\x18\x01 \x01(\x0b\x32+.ThreeShape.CAMair.Api.Protocol.v1.Polyline\x12_\n\x19toothAnatomicalDirections\x18\x02 \x01(\x0b\x32<.ThreeShape.CAMair.Api.Protocol.v1.ToothAnatomicalDirections\x12S\n\ncontactMap\x18\x03 \x01(\x0b\x32?.ThreeShape.CAMair.Api.Protocol.v1.AnatomyItemTypes.DistanceMap*\x88\x01\n\x14\x41natomyItemFacetMark\x12\x08\n\x04None\x10\x00\x12\x10\n\x0cOuterSurface\x10\x01\x12\x15\n\x11\x45nhancedCementGap\x10\x02\x12\r\n\tCementGap\x10\x03\x12\x12\n\x0eMarginLineArea\x10\x04\x12\x1a\n\x16\x45nhancedMarginLineArea\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AnatomyItemTypes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANATOMYITEMFACETMARK']._serialized_start=749
  _globals['_ANATOMYITEMFACETMARK']._serialized_end=885
  _globals['_NEEDEDANATOMYITEMDATA']._serialized_start=102
  _globals['_NEEDEDANATOMYITEMDATA']._serialized_end=276
  _globals['_DISTANCESMAPNEEDEDDATA']._serialized_start=278
  _globals['_DISTANCESMAPNEEDEDDATA']._serialized_end=383
  _globals['_DISTANCEMAP']._serialized_start=385
  _globals['_DISTANCEMAP']._serialized_end=479
  _globals['_ANATOMYITEMDATA']._serialized_start=482
  _globals['_ANATOMYITEMDATA']._serialized_end=746
# @@protoc_insertion_point(module_scope)
