# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ArchModelTypes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ArchModelTypes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x41rchModelTypes.proto\x12\x30ThreeShape.CAMair.Api.Protocol.v1.ArchModelTypes\"\x15\n\x13NeededArchModelData\"\x0f\n\rArchModelData*\x1e\n\x12\x41rchModelFacetMark\x12\x08\n\x04None\x10\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ArchModelTypes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARCHMODELFACETMARK']._serialized_start=114
  _globals['_ARCHMODELFACETMARK']._serialized_end=144
  _globals['_NEEDEDARCHMODELDATA']._serialized_start=74
  _globals['_NEEDEDARCHMODELDATA']._serialized_end=95
  _globals['_ARCHMODELDATA']._serialized_start=97
  _globals['_ARCHMODELDATA']._serialized_end=112
# @@protoc_insertion_point(module_scope)
