# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BoneModelTypes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BoneModelTypes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x42oneModelTypes.proto\x12\x30ThreeShape.CAMair.Api.Protocol.v1.BoneModelTypes\"\x15\n\x13NeededBoneModelData\"\x0f\n\rBoneModelData*\x1e\n\x12\x42oneModelFacetMark\x12\x08\n\x04None\x10\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BoneModelTypes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BONEMODELFACETMARK']._serialized_start=114
  _globals['_BONEMODELFACETMARK']._serialized_end=144
  _globals['_NEEDEDBONEMODELDATA']._serialized_start=74
  _globals['_NEEDEDBONEMODELDATA']._serialized_end=95
  _globals['_BONEMODELDATA']._serialized_start=97
  _globals['_BONEMODELDATA']._serialized_end=112
# @@protoc_insertion_point(module_scope)
