# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import CAMairProtocol_pb2 as CAMairProtocol__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in CAMairProtocol_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CAMairIntegrationStub(object):
    """gRPC service that allows partner integration components to communicate with CAMair.
    CAMair acts as a client while the partner integration component plays the role of the server.
    Consequently, CAMair is responsible for sending the Requests while the integration components send the Responses.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.unary_unary(
                '/ThreeShape.CAMair.Api.Protocol.v1.CAMairIntegration/Connect',
                request_serializer=CAMairProtocol__pb2.ConnectRequest.SerializeToString,
                response_deserializer=CAMairProtocol__pb2.ConnectResponse.FromString,
                _registered_method=True)
        self.GetNeededData = channel.unary_unary(
                '/ThreeShape.CAMair.Api.Protocol.v1.CAMairIntegration/GetNeededData',
                request_serializer=CAMairProtocol__pb2.GetNeededDataRequest.SerializeToString,
                response_deserializer=CAMairProtocol__pb2.GetNeededDataResponse.FromString,
                _registered_method=True)
        self.StartJob = channel.stream_stream(
                '/ThreeShape.CAMair.Api.Protocol.v1.CAMairIntegration/StartJob',
                request_serializer=CAMairProtocol__pb2.StartJobRequest.SerializeToString,
                response_deserializer=CAMairProtocol__pb2.StartJobResponse.FromString,
                _registered_method=True)
        self.GetJobStatuses = channel.unary_stream(
                '/ThreeShape.CAMair.Api.Protocol.v1.CAMairIntegration/GetJobStatuses',
                request_serializer=CAMairProtocol__pb2.JobStatusRequest.SerializeToString,
                response_deserializer=CAMairProtocol__pb2.JobStatusResponse.FromString,
                _registered_method=True)


class CAMairIntegrationServicer(object):
    """gRPC service that allows partner integration components to communicate with CAMair.
    CAMair acts as a client while the partner integration component plays the role of the server.
    Consequently, CAMair is responsible for sending the Requests while the integration components send the Responses.
    """

    def Connect(self, request, context):
        """Exchanges version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNeededData(self, request, context):
        """Queries what data is needed to manufacture the given item.
        Fields marked with 'True' will be provided in the subsequent StartJob call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartJob(self, request_iterator, context):
        """Starts the manufacturing job. CAMair passes all data requested in GetNeededDataResponse.
        Request can be broken down into chunks to match the gRPC max message size.
        Chunks should be grouped by key and merged back using built-in gRPC methods, see the example implementation for details.
        StartJobResponse is expected when all data was received and all job was started or at least allocated.
        StartJobRequest can contain one or multiple items. The response stream should return job identifiers for each individual item.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatuses(self, request, context):
        """Starts the job status transmission for a specific job from the connected partner component
        JobStatusResponse contains job status data definition of current job status of the job in production at the connected partner integration component
        JobStatusResponse stream should can be closed by both CAMair client and partner integration component server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CAMairIntegrationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=CAMairProtocol__pb2.ConnectRequest.FromString,
                    response_serializer=CAMairProtocol__pb2.ConnectResponse.SerializeToString,
            ),
            'GetNeededData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNeededData,
                    request_deserializer=CAMairProtocol__pb2.GetNeededDataRequest.FromString,
                    response_serializer=CAMairProtocol__pb2.GetNeededDataResponse.SerializeToString,
            ),
            'StartJob': grpc.stream_stream_rpc_method_handler(
                    servicer.StartJob,
                    request_deserializer=CAMairProtocol__pb2.StartJobRequest.FromString,
                    response_serializer=CAMairProtocol__pb2.StartJobResponse.SerializeToString,
            ),
            'GetJobStatuses': grpc.unary_stream_rpc_method_handler(
                    servicer.GetJobStatuses,
                    request_deserializer=CAMairProtocol__pb2.JobStatusRequest.FromString,
                    response_serializer=CAMairProtocol__pb2.JobStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ThreeShape.CAMair.Api.Protocol.v1.CAMairIntegration', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ThreeShape.CAMair.Api.Protocol.v1.CAMairIntegration', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CAMairIntegration(object):
    """gRPC service that allows partner integration components to communicate with CAMair.
    CAMair acts as a client while the partner integration component plays the role of the server.
    Consequently, CAMair is responsible for sending the Requests while the integration components send the Responses.
    """

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ThreeShape.CAMair.Api.Protocol.v1.CAMairIntegration/Connect',
            CAMairProtocol__pb2.ConnectRequest.SerializeToString,
            CAMairProtocol__pb2.ConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNeededData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ThreeShape.CAMair.Api.Protocol.v1.CAMairIntegration/GetNeededData',
            CAMairProtocol__pb2.GetNeededDataRequest.SerializeToString,
            CAMairProtocol__pb2.GetNeededDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartJob(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ThreeShape.CAMair.Api.Protocol.v1.CAMairIntegration/StartJob',
            CAMairProtocol__pb2.StartJobRequest.SerializeToString,
            CAMairProtocol__pb2.StartJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatuses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ThreeShape.CAMair.Api.Protocol.v1.CAMairIntegration/GetJobStatuses',
            CAMairProtocol__pb2.JobStatusRequest.SerializeToString,
            CAMairProtocol__pb2.JobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
