# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CrownPonticItemTypes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'CrownPonticItemTypes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CAMairDataTypes_pb2 as CAMairDataTypes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x43rownPonticItemTypes.proto\x12\x36ThreeShape.CAMair.Api.Protocol.v1.CrownPonticItemTypes\x1a\x15\x43\x41MairDataTypes.proto\">\n\x19NeededCrownPonticItemData\x12!\n\x19toothAnatomicalDirections\x18\x02 \x01(\x08\"v\n\x13\x43rownPonticItemData\x12_\n\x19toothAnatomicalDirections\x18\x02 \x01(\x0b\x32<.ThreeShape.CAMair.Api.Protocol.v1.ToothAnatomicalDirectionsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CrownPonticItemTypes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NEEDEDCROWNPONTICITEMDATA']._serialized_start=109
  _globals['_NEEDEDCROWNPONTICITEMDATA']._serialized_end=171
  _globals['_CROWNPONTICITEMDATA']._serialized_start=173
  _globals['_CROWNPONTICITEMDATA']._serialized_end=291
# @@protoc_insertion_point(module_scope)
