# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MajorVersionCheck.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'MajorVersionCheck.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17MajorVersionCheck.proto\x12\x1eThreeShape.CAMair.Api.Protocol\"\"\n GetSupportedMajorVersionsRequest\"I\n!GetSupportedMajorVersionsResponse\x12$\n\x1cserverSupportedMajorVersions\x18\x01 \x03(\x05\x32\xbc\x01\n\x17\x43\x41MairMajorVersionCheck\x12\xa0\x01\n\x19GetSupportedMajorVersions\x12@.ThreeShape.CAMair.Api.Protocol.GetSupportedMajorVersionsRequest\x1a\x41.ThreeShape.CAMair.Api.Protocol.GetSupportedMajorVersionsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MajorVersionCheck_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSUPPORTEDMAJORVERSIONSREQUEST']._serialized_start=59
  _globals['_GETSUPPORTEDMAJORVERSIONSREQUEST']._serialized_end=93
  _globals['_GETSUPPORTEDMAJORVERSIONSRESPONSE']._serialized_start=95
  _globals['_GETSUPPORTEDMAJORVERSIONSRESPONSE']._serialized_end=168
  _globals['_CAMAIRMAJORVERSIONCHECK']._serialized_start=171
  _globals['_CAMAIRMAJORVERSIONCHECK']._serialized_end=359
# @@protoc_insertion_point(module_scope)
