# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import MajorVersionCheck_pb2 as MajorVersionCheck__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in MajorVersionCheck_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CAMairMajorVersionCheckStub(object):
    """gRPC service with a simple handshake-like method serving two major purposes.
    1. Check that connection to the given partner integration component can be established
    2. Find out the major version of the CAMair gRPC protocol supported by the server to rule out potential incompatibility.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSupportedMajorVersions = channel.unary_unary(
                '/ThreeShape.CAMair.Api.Protocol.CAMairMajorVersionCheck/GetSupportedMajorVersions',
                request_serializer=MajorVersionCheck__pb2.GetSupportedMajorVersionsRequest.SerializeToString,
                response_deserializer=MajorVersionCheck__pb2.GetSupportedMajorVersionsResponse.FromString,
                _registered_method=True)


class CAMairMajorVersionCheckServicer(object):
    """gRPC service with a simple handshake-like method serving two major purposes.
    1. Check that connection to the given partner integration component can be established
    2. Find out the major version of the CAMair gRPC protocol supported by the server to rule out potential incompatibility.
    """

    def GetSupportedMajorVersions(self, request, context):
        """Request server-side supported major version of the CAMair gRPC protocol.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CAMairMajorVersionCheckServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSupportedMajorVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSupportedMajorVersions,
                    request_deserializer=MajorVersionCheck__pb2.GetSupportedMajorVersionsRequest.FromString,
                    response_serializer=MajorVersionCheck__pb2.GetSupportedMajorVersionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ThreeShape.CAMair.Api.Protocol.CAMairMajorVersionCheck', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ThreeShape.CAMair.Api.Protocol.CAMairMajorVersionCheck', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CAMairMajorVersionCheck(object):
    """gRPC service with a simple handshake-like method serving two major purposes.
    1. Check that connection to the given partner integration component can be established
    2. Find out the major version of the CAMair gRPC protocol supported by the server to rule out potential incompatibility.
    """

    @staticmethod
    def GetSupportedMajorVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ThreeShape.CAMair.Api.Protocol.CAMairMajorVersionCheck/GetSupportedMajorVersions',
            MajorVersionCheck__pb2.GetSupportedMajorVersionsRequest.SerializeToString,
            MajorVersionCheck__pb2.GetSupportedMajorVersionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
