# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: NetworkDiscovery.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'NetworkDiscovery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16NetworkDiscovery.proto\x12\x1eThreeShape.CAMair.Api.Protocol\"\x1b\n\x19\x43omponentDiscoveryRequest\"t\n\x1a\x43omponentDiscoveryResponse\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12:\n\x08protocol\x18\x03 \x01(\x0e\x32(.ThreeShape.CAMair.Api.Protocol.Protocol*=\n\x14NetworkDiscoveryPort\x12\x19\n\x15\x64o_not_use_this_value\x10\x00\x12\n\n\x05Value\x10\xf3\x33*\x1f\n\x08Protocol\x12\x08\n\x04Http\x10\x00\x12\t\n\x05Https\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'NetworkDiscovery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NETWORKDISCOVERYPORT']._serialized_start=205
  _globals['_NETWORKDISCOVERYPORT']._serialized_end=266
  _globals['_PROTOCOL']._serialized_start=268
  _globals['_PROTOCOL']._serialized_end=299
  _globals['_COMPONENTDISCOVERYREQUEST']._serialized_start=58
  _globals['_COMPONENTDISCOVERYREQUEST']._serialized_end=85
  _globals['_COMPONENTDISCOVERYRESPONSE']._serialized_start=87
  _globals['_COMPONENTDISCOVERYRESPONSE']._serialized_end=203
# @@protoc_insertion_point(module_scope)
