# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RegionConfigurationService.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'RegionConfigurationService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n RegionConfigurationService.proto\x12\x1eThreeShape.CAMair.Api.Protocol\"1\n\x13RegionConfiguration\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"\x1c\n\x1aRegionConfigurationRequest2\xaf\x01\n\x1aRegionConfigurationService\x12\x90\x01\n\x1dGetCurrentRegionConfiguration\x12:.ThreeShape.CAMair.Api.Protocol.RegionConfigurationRequest\x1a\x33.ThreeShape.CAMair.Api.Protocol.RegionConfigurationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RegionConfigurationService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGIONCONFIGURATION']._serialized_start=68
  _globals['_REGIONCONFIGURATION']._serialized_end=117
  _globals['_REGIONCONFIGURATIONREQUEST']._serialized_start=119
  _globals['_REGIONCONFIGURATIONREQUEST']._serialized_end=147
  _globals['_REGIONCONFIGURATIONSERVICE']._serialized_start=150
  _globals['_REGIONCONFIGURATIONSERVICE']._serialized_end=325
# @@protoc_insertion_point(module_scope)
