# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import RegionConfigurationService_pb2 as RegionConfigurationService__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in RegionConfigurationService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RegionConfigurationServiceStub(object):
    """Retrieves the current region configuration for the authenticated user.
    The user's information is extracted from the JWT token in the request  metadata.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCurrentRegionConfiguration = channel.unary_unary(
                '/ThreeShape.CAMair.Api.Protocol.RegionConfigurationService/GetCurrentRegionConfiguration',
                request_serializer=RegionConfigurationService__pb2.RegionConfigurationRequest.SerializeToString,
                response_deserializer=RegionConfigurationService__pb2.RegionConfiguration.FromString,
                _registered_method=True)


class RegionConfigurationServiceServicer(object):
    """Retrieves the current region configuration for the authenticated user.
    The user's information is extracted from the JWT token in the request  metadata.
    """

    def GetCurrentRegionConfiguration(self, request, context):
        """Possible errors:
        - NOT_FOUND (404): If no region configuration is found for the user
        - INTERNAL (500): For any server-side errors
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegionConfigurationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCurrentRegionConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentRegionConfiguration,
                    request_deserializer=RegionConfigurationService__pb2.RegionConfigurationRequest.FromString,
                    response_serializer=RegionConfigurationService__pb2.RegionConfiguration.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ThreeShape.CAMair.Api.Protocol.RegionConfigurationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ThreeShape.CAMair.Api.Protocol.RegionConfigurationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RegionConfigurationService(object):
    """Retrieves the current region configuration for the authenticated user.
    The user's information is extracted from the JWT token in the request  metadata.
    """

    @staticmethod
    def GetCurrentRegionConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ThreeShape.CAMair.Api.Protocol.RegionConfigurationService/GetCurrentRegionConfiguration',
            RegionConfigurationService__pb2.RegionConfigurationRequest.SerializeToString,
            RegionConfigurationService__pb2.RegionConfiguration.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
