# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ScrewRetainedCrownTypes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ScrewRetainedCrownTypes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CAMairDataTypes_pb2 as CAMairDataTypes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dScrewRetainedCrownTypes.proto\x12\x39ThreeShape.CAMair.Api.Protocol.v1.ScrewRetainedCrownTypes\x1a\x15\x43\x41MairDataTypes.proto\"\xca\x01\n\x0f\x41\x62utmentKitData\x12\x15\n\rabutmentKitId\x18\x01 \x01(\t\x12\x17\n\x0f\x61\x62utmentKitName\x18\x02 \x01(\t\x12\x17\n\x0fimplantSystemId\x18\x03 \x01(\t\x12\x19\n\x11implantSystemName\x18\x04 \x01(\t\x12\x1c\n\x14implantSystemVersion\x18\x05 \x01(\t\x12\x13\n\x0bzAxisOffset\x18\x06 \x01(\x01\x12 \n\x18rotateAroundImplantAngle\x18\x07 \x01(\x01\"\x91\x01\n\x1cNeededScrewRetainedCrownData\x12\x1d\n\x15\x65mergenceProfileCurve\x18\x01 \x01(\x08\x12!\n\x19toothAnatomicalDirections\x18\x02 \x01(\x08\x12\x13\n\x0b\x61\x62utmentKit\x18\x03 \x01(\x08\x12\x1a\n\x12implantCoordSystem\x18\x04 \x01(\x08\"\xf7\x02\n\x16ScrewRetainedCrownData\x12J\n\x15\x65mergenceProfileCurve\x18\x01 \x01(\x0b\x32+.ThreeShape.CAMair.Api.Protocol.v1.Polyline\x12_\n\x19toothAnatomicalDirections\x18\x02 \x01(\x0b\x32<.ThreeShape.CAMair.Api.Protocol.v1.ToothAnatomicalDirections\x12_\n\x0b\x61\x62utmentKit\x18\x03 \x01(\x0b\x32J.ThreeShape.CAMair.Api.Protocol.v1.ScrewRetainedCrownTypes.AbutmentKitData\x12O\n\x12implantCoordSystem\x18\x04 \x01(\x0b\x32\x33.ThreeShape.CAMair.Api.Protocol.v1.CoordinateSystem*]\n\x1bScrewRetainedCrownFacetMark\x12\x08\n\x04None\x10\x00\x12\x08\n\x04\x42\x61se\x10\x01\x12\n\n\x06TopCap\x10\x02\x12\r\n\tScrewHole\x10\x03\x12\x0f\n\x0b\x45xitProfile\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ScrewRetainedCrownTypes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCREWRETAINEDCROWNFACETMARK']._serialized_start=846
  _globals['_SCREWRETAINEDCROWNFACETMARK']._serialized_end=939
  _globals['_ABUTMENTKITDATA']._serialized_start=116
  _globals['_ABUTMENTKITDATA']._serialized_end=318
  _globals['_NEEDEDSCREWRETAINEDCROWNDATA']._serialized_start=321
  _globals['_NEEDEDSCREWRETAINEDCROWNDATA']._serialized_end=466
  _globals['_SCREWRETAINEDCROWNDATA']._serialized_start=469
  _globals['_SCREWRETAINEDCROWNDATA']._serialized_end=844
# @@protoc_insertion_point(module_scope)
