# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SplintTypes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SplintTypes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CAMairDataTypes_pb2 as CAMairDataTypes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11SplintTypes.proto\x12-ThreeShape.CAMair.Api.Protocol.v1.SplintTypes\x1a\x15\x43\x41MairDataTypes.proto\"&\n\x10NeededSplintData\x12\x12\n\nmarginLine\x18\x01 \x01(\x08\"M\n\nSplintData\x12?\n\nmarginLine\x18\x01 \x01(\x0b\x32+.ThreeShape.CAMair.Api.Protocol.v1.Polyline*?\n\x0fSplintFacetMark\x12\x08\n\x04None\x10\x00\x12\x10\n\x0cOuterSurface\x10\x01\x12\x10\n\x0cInnerSurface\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SplintTypes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPLINTFACETMARK']._serialized_start=210
  _globals['_SPLINTFACETMARK']._serialized_end=273
  _globals['_NEEDEDSPLINTDATA']._serialized_start=91
  _globals['_NEEDEDSPLINTDATA']._serialized_end=129
  _globals['_SPLINTDATA']._serialized_start=131
  _globals['_SPLINTDATA']._serialized_end=208
# @@protoc_insertion_point(module_scope)
