# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SurgicalGuideTypes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SurgicalGuideTypes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18SurgicalGuideTypes.proto\x12\x34ThreeShape.CAMair.Api.Protocol.v1.SurgicalGuideTypes\"\x19\n\x17NeededSurgicalGuideData\"\x13\n\x11SurgicalGuideData*f\n\x16SurgicalGuideFacetMark\x12\x08\n\x04None\x10\x00\x12\x10\n\x0cOuterSurface\x10\x01\x12\x12\n\x0eSleeveCylinder\x10\x02\x12\x10\n\x0cInnerSurface\x10\x03\x12\n\n\x06Sleeve\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SurgicalGuideTypes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SURGICALGUIDEFACETMARK']._serialized_start=130
  _globals['_SURGICALGUIDEFACETMARK']._serialized_end=232
  _globals['_NEEDEDSURGICALGUIDEDATA']._serialized_start=82
  _globals['_NEEDEDSURGICALGUIDEDATA']._serialized_end=107
  _globals['_SURGICALGUIDEDATA']._serialized_start=109
  _globals['_SURGICALGUIDEDATA']._serialized_end=128
# @@protoc_insertion_point(module_scope)
