"""Generate `docs/err_code_spec.md`'s Error Code Reference table and
`docs/error_codes.json` from the single source of truth, `agent/error_codes.py`.

Scope note: only the "Error Code Reference" table in err_code_spec.md is
managed by this generator. The rest of that file ("Error Response Format",
"Endpoints") is hand-maintained prose describing per-endpoint semantics that
cannot be derived from the registry's five fields (code / http_status /
retryable / owner / note) — it is left untouched by --write.

Usage:
    python -m agent.tools.error_codes --write   # regenerate both artifacts
    python -m agent.tools.error_codes --check   # exit non-zero if stale, exit 0 if up to date
"""

import argparse
import json
import sys
from pathlib import Path

from agent.error_codes import ALL

_REPO_ROOT = Path(__file__).resolve().parents[2]
_MD_PATH = _REPO_ROOT / "docs" / "err_code_spec.md"
_JSON_PATH = _REPO_ROOT / "docs" / "error_codes.json"

_BANNER_START = "<!-- AUTO-GENERATED"
_HEADER_BANNER = (
    "<!-- AUTO-GENERATED (partial): the \"Error Code Reference\" table below is produced by\n"
    "`python -m agent.tools.error_codes --write` from `agent/error_codes.py` — do not hand-edit\n"
    "that table. Everything else in this file (Error Response Format, Endpoints) is\n"
    "hand-maintained prose and is left untouched by --write. -->\n\n"
)

_TABLE_HEADING = "## Error Code Reference"
_TABLE_HEADER_ROW = "| Code | HTTP Status | retryable | 說明 |\n|---|---|---|---|\n"
_SECTION_END = "\n---\n"


def _strip_banner(text: str) -> str:
    if text.startswith(_BANNER_START):
        _, _, remainder = text.partition("-->\n\n")
        return remainder
    return text


def _table_rows() -> str:
    return "\n".join(
        f"| `{spec.code}` | {spec.http_status} | {'true' if spec.retryable else 'false'} | {spec.note} |"
        for spec in ALL
    )


def _render_md() -> str:
    if not _MD_PATH.exists():
        raise FileNotFoundError(
            f"{_MD_PATH} must already exist — this generator only replaces its "
            f'"{_TABLE_HEADING}" table, not the surrounding hand-written sections'
        )
    original = _strip_banner(_MD_PATH.read_text(encoding="utf-8"))
    before, sep, rest = original.partition(_TABLE_HEADING)
    if not sep:
        raise ValueError(f'{_MD_PATH} has no "{_TABLE_HEADING}" section to replace')
    _, end_sep, after_table = rest.partition(_SECTION_END)
    if not end_sep:
        raise ValueError(
            f'{_MD_PATH}: could not find the end of the "{_TABLE_HEADING}" table '
            f'(expected a lone "---" line terminating it)'
        )
    table = f"{_TABLE_HEADING}\n\n{_TABLE_HEADER_ROW}{_table_rows()}\n"
    return f"{_HEADER_BANNER}{before}{table}{_SECTION_END}{after_table}"


def _render_json() -> str:
    payload = {
        "_generated": (
            "AUTO-GENERATED by `python -m agent.tools.error_codes --write` from "
            "agent/error_codes.py — do not edit by hand, edit that file instead."
        ),
        "codes": [
            {
                "code": spec.code,
                "http_status": spec.http_status,
                "retryable": spec.retryable,
                "owner": spec.owner,
                "note": spec.note,
            }
            for spec in ALL
        ],
    }
    return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"


def write() -> None:
    _MD_PATH.write_text(_render_md(), encoding="utf-8", newline="\n")
    _JSON_PATH.write_text(_render_json(), encoding="utf-8", newline="\n")


def check() -> int:
    stale = []
    if not _MD_PATH.exists() or _MD_PATH.read_text(encoding="utf-8") != _render_md():
        stale.append(str(_MD_PATH))
    if not _JSON_PATH.exists() or _JSON_PATH.read_text(encoding="utf-8") != _render_json():
        stale.append(str(_JSON_PATH))
    if stale:
        print("Stale generated file(s). Run: python -m agent.tools.error_codes --write")
        for path in stale:
            print(f"  - {path}")
        return 1
    return 0


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="regenerate the artifacts")
    group.add_argument("--check", action="store_true", help="verify artifacts are up to date")
    args = parser.parse_args(argv)

    if args.write:
        write()
        return 0
    return check()


if __name__ == "__main__":
    sys.exit(main())
