"""FDM (FFF) slicing via PrusaSlicer CLI.

Independent from `sla_operations` — different output format (gcode), different
metadata (filament length / print time vs. resin / layer count).
"""
from __future__ import annotations

import asyncio
import re
from pathlib import Path
from typing import Optional

from .config import PRUSA_SLICER_CLI
from .jobs_fdm import (
    FDMJobStatus,
    get_fdm_input_path,
    get_fdm_job_dir,
    write_fdm_status,
)


# PrusaSlicer writes G-code summary lines like:
#   ; estimated printing time (normal mode) = 1h 23m 45s
#   ; filament used [mm] = 1234.56
_RE_PRINT_TIME = re.compile(
    r"^;\s*estimated printing time\s*\([^)]+\)\s*=\s*(.+)$",
    re.IGNORECASE,
)
_RE_FILAMENT_MM = re.compile(
    r"^;\s*filament used \[mm\]\s*=\s*([\d.]+)",
    re.IGNORECASE,
)


def _parse_duration(text: str) -> Optional[float]:
    """`1h 23m 45s` -> seconds."""
    total = 0.0
    matched = False
    for n, unit in re.findall(r"(\d+(?:\.\d+)?)\s*([dhms])", text):
        matched = True
        v = float(n)
        if unit == "d":
            total += v * 86400
        elif unit == "h":
            total += v * 3600
        elif unit == "m":
            total += v * 60
        elif unit == "s":
            total += v
    return total if matched else None


def _parse_gcode_summary(gcode_path: Path) -> tuple[Optional[float], Optional[float]]:
    """Read the trailing comment block of a PrusaSlicer-emitted G-code file.

    PrusaSlicer puts its summary near the end of the file, so we tail the last
    ~64 KB rather than scanning the whole thing (G-code can be 100+ MB).
    """
    print_time_s: Optional[float] = None
    filament_mm: Optional[float] = None

    try:
        size = gcode_path.stat().st_size
        with open(gcode_path, "rb") as f:
            f.seek(max(0, size - 65536))
            tail = f.read().decode("utf-8", errors="replace")
    except OSError:
        return None, None

    for line in tail.splitlines():
        if print_time_s is None:
            m = _RE_PRINT_TIME.match(line)
            if m:
                print_time_s = _parse_duration(m.group(1))
                continue
        if filament_mm is None:
            m = _RE_FILAMENT_MM.match(line)
            if m:
                try:
                    filament_mm = float(m.group(1))
                except ValueError:
                    pass
        if print_time_s is not None and filament_mm is not None:
            break

    return print_time_s, filament_mm


# Keys whose ini value MUST carry a "%" suffix (PrusaSlicer's coPercent type).
# Other "%-looking" keys like *_fan_speed are coInt 0-100 — plain integer only,
# percent sign would be rejected.
_PERCENT_KEYS = {
    "fill_density",
    "infill_overlap",
}


def _format_ini_value(key: str, v) -> str:
    """Serialize a Python value the way PrusaSlicer's ini parser expects."""
    if isinstance(v, bool):
        return "1" if v else "0"
    if v is None:
        return ""
    if key in _PERCENT_KEYS and not isinstance(v, str):
        return f"{v}%"
    return str(v)


def _write_config_ini(job_id: str, params: Optional[dict]) -> Optional[Path]:
    """Persist user params as a config.ini in the job dir. Returns the path,
    or None if there are no params (so caller can skip --load).
    """
    if not params:
        return None
    ini_path = get_fdm_job_dir(job_id) / "config.ini"
    lines = [
        "# Auto-generated by /api/v2/fdm/jobs/{id}/slice — user overrides",
        "# Each key matches a PrusaSlicer config option (snake_case).",
        "",
    ]
    for key, value in params.items():
        # Skip empty strings — they would override defaults to nothing.
        if value is None or value == "":
            continue
        lines.append(f"{key} = {_format_ini_value(key, value)}")
    ini_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return ini_path


async def run_fdm_slicing(job_id: str, params: Optional[dict] = None):
    """Slice the job's input STL into G-code.

    If ``params`` is provided, the keys are written into ``config.ini`` and
    passed to PrusaSlicer via ``--load``. Otherwise PrusaSlicer falls back
    to its built-in default FFF profile (Original Prusa i3 MK3, 0.4 nozzle,
    generic PLA).
    """
    job_dir = get_fdm_job_dir(job_id)
    input_path = get_fdm_input_path(job_id)
    output_path = job_dir / "output" / "model.gcode"
    stderr_file = job_dir / "stderr.log"

    write_fdm_status(job_id, FDMJobStatus.PROCESSING)

    if input_path is None:
        write_fdm_status(job_id, FDMJobStatus.FAILED, error="Input STL not found")
        return

    ini_path = _write_config_ini(job_id, params)

    cmd = [str(PRUSA_SLICER_CLI)]
    if ini_path is not None:
        cmd += ["--load", str(ini_path)]
    cmd += [
        "--export-gcode",
        "--output", str(output_path),
        str(input_path),
    ]

    try:
        process = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await process.communicate()

        with open(stderr_file, "wb") as f:
            f.write(stderr)

        if process.returncode != 0:
            write_fdm_status(
                job_id, FDMJobStatus.FAILED,
                error=f"PrusaSlicer exit {process.returncode}: "
                      f"{stderr.decode('utf-8', errors='replace')[-500:]}",
            )
            return

        if not output_path.exists():
            write_fdm_status(job_id, FDMJobStatus.FAILED, error="G-code not produced")
            return

        print_time_s, filament_mm = _parse_gcode_summary(output_path)
        write_fdm_status(
            job_id, FDMJobStatus.COMPLETED,
            has_gcode=True,
            estimated_print_time_s=print_time_s,
            filament_used_mm=filament_mm,
        )

    except Exception as e:
        write_fdm_status(job_id, FDMJobStatus.FAILED, error=str(e))
